Install RSpec

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -1,1 +1,5 @@
-bundle exec rake test
+bundle exec rspec
+if [ $? -ne 0 ]; then
+  echo 'RSpec did not run successfully, commit aborted'
+  exit 1
+fi
